DEFAULT_SOURCE_MAPPINGS = {
    "instagram" : "instagram.com",
    "facebook" : "facebook.com",
    "tiktok" : "tiktok.com",
    "tass" : "tass.com",
    "joe" : "joerogan.uk",
    "bloomberg" : "bloomberg.com",
    "snopes" : "snopes.com",
    "candace" : "twitter.com",
    "reuters" : "reuters.com",
    "russian embassy in canada" : "twitter.com",
    "u.s. energy information administration" : "eia.gov",
    "fox" : "foxnews.com",
    "the kremlin" : "kremlin.ru",
    "tweet" : "twitter.com",
    "youtube" : "youtube.com",
    "real raw news" : "realrawnews.com",
    "adimpact.com" : "adimpact.com",
    "jd vance" : "jdvance.com",
    "c-span" : "c-span.org",
    "twitter" : "twitter.com",
    "cbs news" : "cbsnews.com",
    "blog post" : "facebook.com",
    "pat" : "patmccrory.com",
    "associated press" : "apnews.com",
    "russian ministry of defense on telegram (archived)" : "telegram.org",
    "the ministry of foreign affairs of the russian federation" : "mid.ru/en/",
    "gateway pundit" : "thegatewaypundit.com",
    "u.s. department of defense" : "defense.gov",
    "jane timken" : "twitter.com",
    "right side broadcasting network on rumble" : "rsbnetwork.com",
    "nytimes.com" : "new york times",
    "washingtonpost.com" : "washington post",
    "dailymail.co.uk" : "daily mail",
    "yahoo.com" : "yahoo news",
}